name = "kiro-workshop-resume"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
build = { command = "npm run build", cwd = "." }
main = "dist/index.html"

[env.production]
